let techStackList = [
    // "fastapi",
    // "langchain",
    // "langgraph",
    // "pydantic",
    // "react",
    // "pnpm",
    // "cypress",
    // "pytest",
    // "asyncio",
    // "GitHub actions",
    // "Jenkins",
    // "Docker",
    // "Podman",
    // "Kubernetes",
    // "express",
    // "socket.io",
    "Postgresql",
]
